### ISSUE TITLE
[Cmake] Configure called for already existing __init__.py

### ISSUE THREAD

**Issue by ksyy** [jrl-umi3218/jrl-cmakemodules#144]
Hi,

In https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/python.cmake#L161, the `__init__.py` are created for each python module of the calling project, along with some other operations.

A problem arises when the source and binary directory are the same (for example in *robotpkg*), because the `__init__.py` already exists and is overwritten.

For example, because of a recent change of the build directory of *sot-core-v3* in *robotpkg*, https://github.com/stack-of-tasks/sot-core/blob/master/src/dynamic_graph/sot/core/__init__.py is overwritten before the installation, leading to many `import error`…

Should we modify `python.cmake` to call `CONFIGURE` only if no `__init__.py` exists in the directory or is it a feature and it is the `sot's CMakeLists.txt` (and maybe other projects) that should not have called this macro?

**Comment by gergondet** [comment]
There is a break in `sot-core` here that is just highlighted by having the source and binary directories.

In regular conditions, there would be two `__init__.py` installed in the same place:
- `DYNAMIC_GRAPH_PYTHON_MODULE("sot/core" ${SOTCORE_LIB_NAME} wrap)` will install the `__init__.py` it generated in `${PYTHON_SITELIB}/dynamic_graph/sot/core
- [sot-core CMakeLists.txt](https://github.com/stack-of-tasks/sot-core/blob/master/src/CMakeLists.txt#L243) does the exact same thing

It probably always worked in the past (8 years!) because the later is run after the former. The call to `DYNAMIC_GRAPH_PYTHON_MODULE` is probably unneeded in `sot-core` nowadays but you'd probably want to check with them directly :)
