### ISSUE TITLE
Pollution caused by old library versions

### ISSUE THREAD

**Issue by gabrielebndn** [jrl-umi3218/jrl-cmakemodules#189]
As of now, `make` generates libraries called
  `lib<libname.so>.<git tag>-<?>-<commit hash>[-dirty]`
and then creates a symlink `<libname.so>` to the newly-built library version (if there are no git tags, the name is `<libname.so>.UNKNOWN`).
This happens in the build directory.
Similarly, when doing `make install`, `lib<libname.so>.<git tag>-<?>-<commit hash>[-dirty]` is copied to the install directory and a symlink to it also installed/updated.

However, the old library versions *are not deleted*. Neither in the build directory when doing `make`, nor in the install directory when doing `make install`.

I don't know if this was intentional, but I think it does not work well. This causes a bunch of spurious files to just remain there and waste space (and screen space when doing `ls`). The amount of files can be considerate when doing development, since a new library is installed with basically every new commit.

`make uninstall` won't work either, because it will only remove the things which where installed with the last installation, not the old versions. `make clean` won't work either.

I believe that, when installing a new version, the old one should be removed.

**Comment by jcarpent** [comment]
This behavior is expected. You should always perform a make uninstall before a make install. This is the only way to not increase the number of versions in the current install directory.

**Comment by gabrielebndn** [comment]
I'll try to remember that, then...
I guess having make uninstall remove all versions would defeat the purpose, right?
Is there no way to remove ALL versions?

**Comment by jcarpent** [comment]
Make uninstall will remove all the versions previously installed by make install. It won’t take into account the complete history.
You have to do that manually. 
What can be done is to add a new make option to remove all the current versions to simplify the deletion.

**Comment by gabrielebndn** [comment]
That's what I was thinking. An option for that would be nice. And the same for make clean

**Comment by gabrielebndn** [comment]
To clarify what @jmirabel said (and just explained me), this behaviour actually comes from the SOT. I second the second point (or rather, the other way around: an option to disable this). But this is a matter of the SOT. I will close this issue as this is not the appropriate place to talk about it

**Comment by olivier-stasse** [comment]
The delete option is a bit dangerous as you do not if other libraries are linked with this library.

The reason is was done was mostly to avoid that somebody not handling properly his environment variables would messed up with other libraries installed in the system. If you have two libraries with the same ABI same version BUT not with the same algorithm then the link is done quietly. At the integration level this is a pain.

If I am not mistaken Gabriele you are doing the make install to install python files and not the library.

IMHO we are a make python install to install your python module rather than changing the way we handle C++ library without a strong rationale behind it. 

I am fine with option of removing intermediate library but do not expect that the build system will be able to detect that another library is linked over it.
