### ISSUE TITLE
Moving from PKG-CONFIG to FULL CMAKE export - Opening the debate

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#266]
Dear all,

Following some discussions (informal or formal) around the issue of: should we continue using pkg-config WHILE new features embed in Cmake >= 3 are now making correctly the job and simplifying a LOT the packaging of advanced projects?
It would be worthy to mention here the pro and the cons of such move, and maybe the idea of creating a new cmake-module with advanced features (versioning, releases, portability, etc.) and by the way, stopping the development of this one.

What are your opinions?

**Comment by jmirabel** [comment]
There is no conflicts between the two options CMake / pkg-config. You can easily develop the CMake based configuration version, without leaving pkg-config version on the side.

In my opinion, the question is:
- **whether there is a need to implement the CMake based configuration**
- **and whether it should be done within this repository**.

My opinion is *yes* to both questions.

**Comment by nim65s** [comment]
This means dropping support for 14.04 everywhere. Therefore we could also drop support for some old boost versions.

**Comment by olivier-stasse** [comment]
I agree with both. After trying a bit with three repositories, I think this should drastically simplified the jrl-cmakemodules repository. I would suggest to remove any use of pkg-config as manipulating variables as strings seems to be now a bad practice and was an endless source of problems. 

Switching to the CMake package policy and then generating pc file seems to me a good solution. 
But this seems to show that the new version of jrl-cmakemodules might be drastically different from the current one.

**Comment by haudren** [comment]
After fighting a little bit with the new paradigm, I found it worked quite well for us, and I dropped `pkg-config` entirely, except when writing `FindXXX.cmake`. So I'm all for it, although I am not really an active user of `jrl-cmakemodules` anymore.

**Comment by jcarpent** [comment]
> This means dropping support for 14.04 everywhere. Therefore we could also drop support for Boost < 1.58 & Eigen < 3.2.92

I think this can be considered independant from the package build. It is not related to Ubuntu 14.04 specifically.

**Comment by gergondet** [comment]
I've moved all our code to the new approach and it's much nicer:

- you get the ability to specify components easily
- you can export CMake macros
- your consumer don't need to have the jrl-cmakemodules as a submodule to consume everything correctly, so this is greatly simplified

The only thing I'm missing is the occasional time when I want to compile a quick test/example, before I would sometimes do:

```bash
$ g++ -o foo foo.cpp `pkg-config --cflags --libs mc_rtc
```

whereas now I need to have a sandbox CMake project on the side for such things.

I don't think we would gain much from developing these modules from scratch as the only inconvenience (imho) is that the default `.pc` is now useless.

I think we could get around that by generating a useful `.pc` file from a given target and overwrite the one generated by the project (basically extracting compile/link flags from the target) with a new macro (e.g. `make_pc_from_target(NAME)` and an option to skip the default `.pc` generation.

**Comment by jcarpent** [comment]
@gergondet I do not see how to do the export of a target (with dependencies) from CMake directly. Do you have some hints?

**Comment by olivier-stasse** [comment]
IMHO the code of @gergondet is based on the following tutorial:
https://cmake.org/cmake/help/latest/guide/tutorial/index.html#adding-export-configuration-step-11

I am currently working on switching the SoT to cmake export.
It is a bit of pain mostly due to some badly written FindXXX.cmake files shipped on 16.04LTS,
and due to the fact that I want to be able to build through catkin-tools with the least of modification.

Mostly the problematic FindXXXc.make files where the ones that do not follow the recommended pattern.

**Comment by gergondet** [comment]
> @gergondet I do not see how to do the export of a target (with dependencies) from CMake directly. Do you have some hints?

It's targets all the way down :turtle:. What matters is to get the targets you depend upon into your CMake instance.

No. I'm using the jrl-cmakemodules to take care of everything:

https://jrl-cmakemodules.readthedocs.io/en/master/pages/cmake-packages.html

(this boils down to the same technique as in the tutorial linked by @olivier-stasse but it's much simpler)

The two key points in the example are:

- `set(PROJECT_USE_CMAKE_EXPORT TRUE)` which makes sure that `setup_project_package_finalize()` is called (it's not the default behavior because it would fail if nothing is exported). The main point of this macro is to install the export file.

- `add_project_dependency(MyDependency REQUIRED)` will call `find_package` with the provided arguments and append a call to `find_package(MyDependency REQUIRED)` (or `find_dependency` from CMake 3.12) in the `${PROJECT_NAME}Config.cmake` that is generated by the jrl-cmakemodules. This ensures that when someone call `find_package(jrl-cmakemodules-minimum-working-example)` he also gets the targets from `MyDependency` and everything works smoothly

Extra things to note:

- `PROJECT_EXTRA_MACROS` is not used in the example but it allows to append CMake code to the generated config script

- if you need a build-only dependency you use a stand-alone `find_package`. Normally you can call `find_package` multiple times without breaking anything (typically, I have `add_project_dependency(Boost REQUIRED COMPONENT filesystem)` in the main script and `find_package(Boost REQUIRED COMPONENT unit_test_framework)` in the tests folder. That's also useful for optional dependencies that depends on a library that then becomes required.

```cmake
find_package(OptionalPackage QUIET)
if(${OptionalPackage_FOUND})
  add_project_dependency(OptionalPackage REQUIRED)
endif()
```

> It is a bit of pain mostly due to some badly written FindXXX.cmake files shipped on 16.04LTS,
and due to the fact that I want to be able to build through catkin-tools with the least of modification.

You can use `PACKAGE_EXTRA_MACROS` to work-around such issues, for example: https://github.com/jrl-umi3218/mc_rbdyn_urdf/blob/master/CMakeLists.txt#L29

In this example we want to get `tinyxml2`. In recent versions, it ships with a CMake script so that's great. In older version it doesn't so we ship our own simple script to find it (I strongly advice to prefix it with the project name so it doesn't conflict with CMake's own scripts) and install it along with the project Config script. You can ship more recent `FindXXX.cmake` this way as well

**Comment by wxmerkt** [comment]
I am very much in favour of switching to CMake - there are numerous issues that pop up with the existing pkg-config builds (e.g. currently again some "libdir" inconsistencies). However, I wonder if a jrl-cmakemodules is required - the majority of projects will work just fine with CMake-out-of-the-box. I don't think the heavy use of macros as currently is doing us any favour.

**Comment by olivier-stasse** [comment]
Dear @wxmerkt after pushing forward the tests with what @gergondet proposed, I think that having macros will be very convenient to handle:
 * recursive dependencies. This is not handled by the tutorial but it is quite elegantly done by the current extension in jrl-cmakemodules wrote by @gergondet without adding any lines. 
 * release operations. I really want to keep all the checking that is done before releasing.
 * making sure that the version are coherent for package.xml as we mentionned.

The alternative to a submodule is to have either catkin packages or cmake packages included.
 * The first one would need to make our package comply with the ros standard. This has consequences on the file and directory naming which are far beyond what we want to handle.
 * The second one implies that any modification on this package will  be propagate to all the repositories. The current system allows each package to be consistent with one version of jrl-cmakemodules, and avoid breaking unecessarily some package.

**Comment by wxmerkt** [comment]
> recursive dependencies

This should be handled if it is linked public? It may not be part of the tutorial yet but I think it should work with CMake targets?

> release operations. I really want to keep all the checking that is done before releasing.

I agree, a release makefile is a different story. It does not require macros for the main CMakeLists.

> making sure that the version are coherent for package.xml as we mentionned.

The release makefile can take care of this - no need for macros at the CMake level.

**Comment by jmirabel** [comment]
> This should be handled if it is linked public?

Do you talk about binary linkage between executables ? If yes, it does not contain all the information. 

> It may not be part of the tutorial yet but I think it should work with CMake targets?

I don't think CMake targets can handle recursive dependencies by themselves. The issue is when you generate CMake files like Config.cmake, Target.cmake and Version.cmake. Let's say you have 3 packages A, B, C, where C depends on B and B on A.
In C cmakelists, you declare the dependency to B and you would like the dependency to A to be implicit. Thus, it has to go into BConfig.cmake. This is were a macro is needed.

**Comment by gergondet** [comment]
> This should be handled if it is linked public? It may not be part of the tutorial yet but I think it should work with CMake targets?

The CMake targets work out of the box. The problem is to import the package recursively.

For example, say you have (for simplicity sake when I say links I mean a `PUBLIC` link in CMake):
- Project A with libA (exported as A::libA)
- Project B with libB (exported as B::libB), libB links with A::libA
- Project C with libC, libC links with B::libB, CMake mechanism makes sure that it will also link with A::libA

In Project C, you do `find_package(B REQUIRED)` and this gets you `B::libB` (great). However, it doesn't get you `A::libA` because you also need to have someone calling `find_package(A REQUIRED)` somewhere.

With the `add_project_dependency(A REQUIRED)` in the project B, it will append a call to `find_package(A REQUIRED)` in `BConfig.cmake` so that it works flawlessly.

The typical way to do the same thing in bare CMake is to add the correct `find_package` call in your `BConfig.cmake.in`. Which means duplicating the call that you are already making in your main script. You can envision the issue when it's updated in your main CMake but not in the one you distribute.

I don't think the usage of macros is a bad thing in CMake. It allows to make a very expressive build configuration script for our common use-cases.

You can compare the [minimal example](https://jrl-cmakemodules.readthedocs.io/en/master/pages/cmake-packages.html#minimal-working-example-with-cmake-packages) with a similar native CMake script. Just generating the Config script is about as many lines as the full example and I'm not including `doc`, `uninstall` and `release` targets which are also nicely generated by just `include(cmake/base.cmake)`

**Comment by jcarpent** [comment]
Seems to be solved now.
