### ISSUE TITLE
Adding support for generic pkg-config

### ISSUE THREAD

**Issue by jcarpent** [jrl-umi3218/jrl-cmakemodules#287]
According to these new lines:

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/8e87406799ea10cfeb90a56f84f3e1ef9c049753/Config.cmake.in#L11

one's cannot use the exported file in extra jrl-cmakemodules contexts if the target contained some pkg dependencies. To make easy the compatibility with these extra situations, I would suggest adding an else statement considering the generic case. @jmirabel @gergondet What do you think?

**Comment by jmirabel** [comment]
The sequence of find_package is mandatory because they may declare imported targets, which will be added dependency.

The sequence of ADD_REQUIRED_DEPENDENCY should be completely useless as the PKG_CONFIG_USE_DEPENDENCY adds the relevant flags to the target, which **can be** exported. To have them exported correctly, you must set [PROJECT_USE_KEYWORD_LINK_LIBRARIES](https://jrl-cmakemodules.readthedocs.io/en/master/pages/base.html#variable:PROJECT_USE_KEYWORD_LINK_LIBRARIES) to true. This is annoying since:
- it applies to all calls to PKG_CONFIG_USE_DEPENDENCY
- it triggers a cmake policy warning (https://cmake.org/cmake/help/latest/policy/CMP0022.html).

In my opinion, we should:
- remove the use of ADD_REQUIRED_DEPENDENCY (optional). It is merely informative.
- add a PUBLIC/PRIVATE argument to PKG_CONFIG_USE_DEPENDENCY.
