### ISSUE TITLE
CMake-exports & Eigen3

### ISSUE THREAD

**Issue by nim65s** [jrl-umi3218/jrl-cmakemodules#331]
Hi,

I tried to use `ADD_PROJECT_DEPENDENCY(Eigen3 3.2.0)`, and it failed on 16.04, with:

```
CMake Warning at cmake/package-config.cmake:69 (find_package):
Could not find a configuration file for package "Eigen3" that is compatible
with requested version "3.2.0".

The following configuration files were considered but not accepted:

/usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown

Call Stack (most recent call first):
CMakeLists.txt:29 (ADD_PROJECT_DEPENDENCY)
```

So I guess the CMake version of 16.04 is not compatible with the Eigen3Config.cmake of 16.04.

@olivier-stasse already got the same issue, but I wanted to be sure that this is a known limitation.

Should we document that for some dependencies / platforms, we can't use this shiny new `ADD_PROJECT_DEPENDENCY`, or is it better to try to fix this ?

**Comment by gergondet** [comment]
> So I guess the CMake version of 16.04 is not compatible with the Eigen3Config.cmake of 16.04.

The problem is that on Xenial, the package does not ship with `/usr/lib/cmake/eigen3/Eigen3ConfigVersion.cmake` as it does in more recent distributions and CMake cannot determine what version is installed.

It will work if you just use `add_project_dependency(Eigen3)` and check the version another way (e.g. relying on `EIGEN3_VERSION_STRING` but this is a legacy variable so it might disappear in the future) or just drop the version requirement here (I'm pretty sure no version of Eigen 3 before 3.2.0 ships a CMake configuration file but I haven't checked) 

Note: I personally use the following to find Eigen because when installed from source on1 Windows, Eigen will add itself to the cmake package register wrongly and report the wrong targets

```cmake
find_package(Eigen3 QUIET NO_CMAKE_PACKAGE_REGISTRY)
if(Eigen3_FOUND)
  add_project_dependency(Eigen3 REQUIRED NO_CMAKE_PACKAGE_REGISTRY)
else()
  add_project_dependency(Eigen3 MODULE REQUIRED)
endif()
```

**Comment by gergondet** [comment]
> Should we document that for some dependencies / platforms, we can't use this shiny new ADD_PROJECT_DEPENDENCY, or is it better to try to fix this ?

This is definitely true. Many projects don't support `find_package` or only support it in recent versions. In my opinion the simplest approach is to handle this on a case-by-case basis, fall back to a more "traditional" way of finding the dependencies  and provide an equivalent target to that provided by recent versions.

For example: [nanomsg](https://github.com/jrl-umi3218/mc_rtc/blob/master/CMakeModules/Findmc_rtc_3rd_party_nanomsg.cmake) or [geos](https://github.com/jrl-umi3218/mc_rtc/blob/master/CMakeModules/Findmc_rtc_3rd_party_geos.cmake)

Maybe it should be clearly noted in the doc and in the mind of the jrl-cmakemodules users that `add_project_dependency` is just a wrapper around the `find_package` call with all the caveats it entails

**Comment by nim65s** [comment]
Thanks for your inputs :)

For my current use-case, I don't remember why I had this 3.2.0, and yes this makes no sense in our current ecosystem to check for this version.

For the documentation, I'll open a small PR.
