### ISSUE TITLE
linking dynamic graph modules with libpython

### ISSUE THREAD

**Issue by proyan** [jrl-umi3218/jrl-cmakemodules#88]
Hi

I am packaging dynamic-graph-python for debian, and found some issues when creating python modules with cmake. Specifically, during linking of libpython with the python modules.

**The issue**: Debian warns against linking against libpythonX.Y, as /usr/bin/pythonX.Y already contains the full python runtime (atleast for debian and ubuntu) From the _[Debian Python Policy](https://www.debian.org/doc/packaging-manuals/python-policy/ch-module_packages.html)_:

>  Some distributions link extensions to libpython, but this is not the case in Debian as symbols might as well be resolved by /usr/bin/pythonX.Y which is not linked to libpython. 

**The warning**: 

>  dh_python2:427: public extension linked with libpython2.7: _library_name_.so

**The solution**: The solution would be to remove ` TARGET_LINK_LIBRARIES(${PYTHON_MODULE} ${LIBRARYNAME} ${PYTHON_LIBRARY})` from https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/python.cmake#L113

**Comment by jcarpent** [comment]
This problem seems to be solved with the addition of TARGET_LINK_BOOST_PYTHON macro which helps the linkage of boost python with undefined symbols concerning the Python symbols.

The idea is the following. When creating a library necessitating a dependence on Python lib, one must link again Python decencies with undefined symbols. Python interpreter must then demystify the right Python libs he has to use. 
In the context of executables, it is an other matter: one has to link against a proper Python libs.

Please refer to TARGET_LINK_BOOST_PYTHON in boost.cmake for a complete example.
