### ISSUE TITLE
Version number is not computed if git is not found

### ISSUE THREAD

**Issue by aescande** [jrl-umi3218/jrl-cmakemodules#91]
This is half a problem of jrl-cmakemodules, half a problem of the way we write our CMakeLists.

As of now, the version number of a library (that will be used to generate the .pc) can be computed solely based on git tags. This gives a rich version number which includes the exact commit used for generating the library.
Because we rely on this behavior, we (almost?) never set PROJECT_VERSION in the CMakeLists.

As a consequence, if git is not found (and there are several user scenarios in which this can happen), the version will be set to UNKNOWN-dirty. This is problematic for subsequent use of a library, when a minimum version number is required.

One solution would be to simply set PROJECT_VERSION in the library's CMakeLists, but, due to the actual logic in base.cmake and version.cmake, it will override the richer git-computed version number, changing the actual number whether git is found or not.
The alternative is to change this logic to have the git-computed version take precedence over PROJECT_VERSION, and fallback to PROJECT_VERSION only when git is not found. Possibly, we can add an error when neither git nor PROJECT_VERSION is found to enforce the generation of a number.

If nobody objects, I'll make the changes of the alternative.

**Comment by olivier-stasse** [comment]
:+1:

**Comment by thomas-moulard** [comment]
disclaimer: giving out some context and my personal opinion, I am no involved in this project anymore so please feel free to do whatever seems best for you :)

version.cmake line 58 to 61 look for a .version at the root of the project which has the precedence over the git information.

It may be broken but the major problem with using PROJECT_VERSION is that if you use the current scheme then the version number depends on the number of commit since the last tag. And if PROJECT_VERSION is set into the CMakeLists.txt then you just cannot have coherent versioning as you need to commit this information which will in turn change the version number.

The approach I would recommend is instead to just generate this file when needed.

The current approach to generate this file is here:
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/dist.cmake#L44

It is Linux-specific but making a similar system for Windows should not be too hard.

Also, the initial reason why the PROJECT_VERSION has not been chosen is that I am quite sure that no one will maintain this flag, so as no information is better than bad information, I would rather go with setting 0.0 as the default PROJECT_VERSION in case the version cannot be determined.

**Comment by bchretien** [comment]
> As a consequence, if git is not found (and there are several user scenarios in which this can happen), the version will be set to UNKNOWN-dirty.

Could you clarify these scenarios?

We can distinguish 2 cases of installed packages:
* release version,
* development version.

As @thomas-moulard explained, the generation of the `.version` is only done for release tarballs. If we take the example of [RobOptim releases](https://github.com/roboptim/roboptim-core/releases/tag/v3.2),  we have:

* GitHub's `Source code (*)` tarballs which are mere unprocessed snapshots. They do not contain either submodules or Git information, so they're useless (no pulled `jrl-cmakemodules`, no `.version`, etc.). This is a [known limitation](http://stackoverflow.com/questions/17847892/download-git-submodules-for-tarball) of GitHub.
* `roboptim-core-3.2.tar.*` which were generated with the `jrl-cmakemodules`, and contain the proper generated `.version` and the submodule files.

The release tarball generation works on Linux, and should work on Mac OS X as well. I doubt that many people use, or even know the existence of that feature though. Still, it has worked as expected for our use cases, and can probably be made user-friendlier (we could make `GPG` optional for instance).

Then we have the development versions. I agree with setting the version to `0.0.0` or similar rather than `UNKNOWN`. That way, we can always rely on the `PROJECT_VERSION` variable. I think we should also consider being able to do the following:

```cmake
set_target_properties(mylib PROPERTIES
  SOVERSION "${PROJECT_VERSION_MAJOR}"
  VERSION "${PROJECT_VERSION}")
```
For the moment, we only define `PROJECT_VERSION`, and `PROJECT_VERSION_{MAJOR|MINOR|PATCH|TWEAK}` are not set.  CMake >= 3.0 can handle this if the version number is provided to `project(...)` (see [CMP0048](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html#policy:CMP0048)). For backwards compatibility with CMake 2.8, we could do that ourselves.

A note on tags: we recently had our private repositories moved, and the person in charge of moving them forgot to push tags (`git push --tags`). This is easy to forget, and as a result broke the library versioning.

**Comment by gergondet** [comment]
I think there is some misunderstanding here. The goal is not to get rid of the tag-based version computation or to rely more heavily on `PROJECT_VERSION` (e.g. for libraries versionning) but to change  the current priority levels when it comes to the computation of the version.

Currently, it is ordered like this:
1. `PROJECT_VERSION` is defined, this is the version [base.cmake#L134](https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/base.cmake#L134). If not, we go into `VERSION_COMPUTE`
2. If a `.version` file is present at the root of the directory then it is the `PROJECT_VERSION`.
3. Otherwise we rely on `git` to compute the version number and set it as `PROJECT_VERSION`

Now a problem arises when `git` is not in your path and you didn't provide it manually to cmake (or you simply don't have `git` on your system). This will most likely only happen on a Windows platform as the default installation does not put git in your path (there is some well motivated reasons behind this behavior). This creates problem later as you install libraries with an `UNKNOWN` version but require them in client code with a minimum version `x.y`.

(Note: while this is a Windows-specific problem now, this may also arise when/if full archive can be downloaded from github without the sub-module issue mentioned by @bchretien)

The proposal is to change the priority so that we always go into `VERSION_COMPUTE` and:
1. If a `.version` file is present then it is the `PROJECT_VERSION`
2. If `git` is found then `PROJECT_VERSION` is computed
3. Otherwise, it relies on the user-defined `PROJECT_VERSION`

Importantly, it means that it is not expected that `PROJECT_VERSION` is updated with every commit but rather at the same time as tags are updated.

Finally, we might consider this is the user's fault for not providing a location for his/her `git` executable and raise a cmake error in that case.

**Comment by bchretien** [comment]
@gergondet absolutely, but I think we might as well clarify what we have, and what could be improved while we're reviewing the current version system.

:+1: for the new priority. `.version` should indeed take priority as it is only set for releases. We could imagine adding checks for consistency: for example, a user creates a `2.0` release, but the user-defined `PROJECT_VERSION` is still set to `1.3`. This would be misleading for anyone reading the source code.

I still think we should consider providing major/minor/patch version numbers for `.so/.dll` versioning. This could also be made available in the source code for compile-time checks by updating `config.hh.cmake`. We can open a new issue for that specific question.

**Comment by jcarpent** [comment]
I think this issue is solved.
@aescande Feel free to reopen it if needed.
